common_misspellings = {
    # Spelling errors
    "definately": ["definitely"],
    "seperate": ["separate"],
    "recieve": ["receive"],
    "occured": ["occurred"],
    "untill": ["until"],
    "wich": ["which"],
    "tommorow": ["tomorrow"],
    "thier": ["their"],
    "wierd": ["weird"],
    "accomodate": ["accommodate"],
    "arguement": ["argument"],
    "beleive": ["believe"],
    "goverment": ["government"],
    "restarant": ["restaurant"],
    "enviroment": ["environment"],
    "concious": ["conscious"],
    "embarass": ["embarrass"],
    "harasment": ["harassment"],
    "occurence": ["occurrence"],
    "commited": ["committed"],
    "neccessary": ["necessary"],
    "independant": ["independent"],
    "adress": ["address"],
    "dissapear": ["disappear"],
    "existince": ["existence"],
    "happend": ["happened"],
    "lonly": ["lonely"],
    "suprise": ["surprise"],
    "truely": ["truly"],
    "wich" : ["which"],

    # Missing apostrophes / contractions
    "youre": ["you're"],
    "dont": ["don't"],
    "doesnt": ["doesn't"],
    "cant": ["can't"],
    "wont": ["won't"],
    "isnt": ["isn't"],
    "arent": ["aren't"],
    "wasnt": ["wasn't"],
    "werent": ["weren't"],
    "couldnt": ["couldn't"],
    "shouldnt": ["shouldn't"],
    "wouldnt": ["wouldn't"],
    "im": ["I'm"],
    "ive": ["I've"],
    "ill": ["I'll"],
    "id": ["I'd"],
    "lets": ["let's"],
    "thats": ["that's"],
    "whos": ["who's"],
    "whats": ["what's"],
    "heres": ["here's"],
    "theres": ["there's"],
    "itll": ["it'll"],
    "itd": ["it'd"],

    # Informal shorthand
    "u": ["you"],
    "r": ["are"],
    "ur": ["your", "you're"],
    "pls": ["please"],
    "thx": ["thanks"],
    "wat": ["what"],
}
